[package]
name = "casein"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2018"

[dependencies]
gouache = { path = "../gouache" }

[dev-dependencies]
gl = "0.11.0"
glutin = "0.21.0"
